#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov  3 14:09:49 2020

@author: xiaofan
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
from sklearn.datasets import load_wine
from sklearn import tree
from sklearn.model_selection import train_test_split
wine = load_wine()
X = wine.data[:, :2] # 只选取数据集前两个特征
y = wine.target
X_train,  X_test, y_train, y_test = train_test_split(X, y)
clf = tree.DecisionTreeClassifier(max_depth=3) # 问的问题数量越多，决策树越深
clf.fit(X_train, y_train)
x_min, x_max = X_train[:, 0].min() - 1, X_train[:, 0].max() + 1
y_min, y_max = X_train[:, 1].min() - 1, X_train[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, .02),
                     np.arange(y_min, y_max, .02))
Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)
cmap_light = ListedColormap(['#FFAAAA', '#AAFFAA', '#AAAAFF']) #background
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])
plt.figure()
plt.pcolormesh(xx, yy, Z, cmap=cmap_light)
plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold, edgecolors='k', s=20)
plt.xlim(xx.min(), xx.max())
plt.ylim(yy.min(), yy.max())
plt.title('Classifier: max_depth = 3')
#%%画不出决策树
# import graphviz
# from sklearn.tree import export_graphviz
# export_graphviz(clf, out_file="wine.dot", class_names=wine.target_names,
#                 feature_names=wine.feature_names[:2], impurity=False, filled=(True))
# with open("wine.dot") as f:
#     dot_graph = f.read()
# graphviz.Source(dot_graph)
#%%随机森林RF和梯度上升GBDT(gradient boosted decision trees)
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=4, random_state=8)
forest.fit(X_train, y_train)
Z1 = forest.predict(np.c_[xx.ravel(), yy.ravel()])
Z1 = Z1.reshape(xx.shape)
plt.figure()
plt.pcolormesh(xx, yy, Z1, cmap=cmap_light)
plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold, edgecolors='k', s=20)
plt.title('Classifier: RandomForest')
#%%
import pandas as pd
adult = pd.read_csv('adult.csv', header=None, index_col=False,
                    names=['年龄', '单位', '权重', '学历', '受教育时长', '婚姻', '职业',
                           '家庭', '种族', '性别', '资产所得', '资产损失', '周工作时长', '原籍', '收入'])
display(adult.head())
# convert string text to value
adult_dummies = pd.get_dummies(adult)
print('样本原始特征:\n', list(adult.columns), '\n')
print('虚拟变量特征:\n', list(adult_dummies.columns), '\n')
#%%
display(adult_dummies.head())
features = adult_dummies.loc()



