


-- 返回最高工资
SELECT DISTINCT FIRST_VALUE(salary) OVER (
	ORDER BY salary DESC
	RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "HIGHEST"
FROM employees;


-- 按部门的最高工资
SELECT DISTINCT department_id, FIRST_VALUE(salary) OVER (
	PARTITION BY department_id 
	ORDER BY salary DESC
	RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "HIGHEST"
FROM employees
WHERE department_id in (10,20)
ORDER BY department_id;

